/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_chapters_ichi_rawExample_Simple */

#ifndef _Included_demo_chapters_ichi_rawExample_Simple
#define _Included_demo_chapters_ichi_rawExample_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_chapters_ichi_rawExample_Simple
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_chapters_ichi_rawExample_Simple_init
  (JNIEnv *, jobject);

/*
 * Class:     demo_chapters_ichi_rawExample_Simple
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_chapters_ichi_rawExample_Simple_uninit
  (JNIEnv *, jobject);

/*
 * Class:     demo_chapters_ichi_rawExample_Simple
 * Method:    loadByID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_demo_chapters_ichi_rawExample_Simple_loadByID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     demo_chapters_ichi_rawExample_Simple
 * Method:    getLegacyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_chapters_ichi_rawExample_Simple_getLegacyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
